apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookreview-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookreview-api
  template:
    metadata:
      labels:
        app: bookreview-api
    spec:
      containers:
      - name: api
        image: 222634358787.dkr.ecr.us-east-1.amazonaws.com/bookreview-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        env:
        - name: DB_HOST
          value: "bookreview-db.clk40aommbmi.us-east-1.rds.amazonaws.com"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DB_NAME
          value: "bookreview"
